object LyricShowForm: TLyricShowForm
  Left = 142
  Top = 635
  Cursor = crSizeAll
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  ClientHeight = 80
  ClientWidth = 751
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -47
  Font.Name = 'Tahoma'
  Font.Style = [fsBold]
  OldCreateOrder = False
  Visible = True
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 57
end
